#!/usr/bin/env python
import sys, os
from waflib.extras.test_base import summary


def options(opt):
    opt.load('compiler_cxx')
    opt.load('boost')
    opt.load('gtest')

def configure(cfg):
    cfg.load('compiler_cxx')
    cfg.load('boost')
    cfg.load('gtest')

    cfg.check_boost(
            lib='system',
            uselib_store='BOOST')

def build(bld):
    bld(
        target          = 'main',
        features        = 'cxx cxxprogram gtest',
        source          = bld.path.ant_glob('*.cc'),
        use             = ['pythonic', 'BOOST'],
        install_path    = 'bin',
        cxxflags        = [
                '-g',
                '-O0',
                '-std=c++0x',
                '-Wall',
                '-Wextra',
                '-pedantic',
            ],
        includes       = '.',
    )

    bld.add_post_fun(summary)
